# utils/state.py
from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class Retrieved_docs(BaseModel):
    doc_id: str = Field(description="ID of the retrieved document")
    content: str = Field(description="Content of the retrieved document")
    metadata: dict = Field(default_factory=dict, description="Metadata associated with the document")
    is_relevant: bool = Field(default=True, description="Indicates if the document is relevant to the query")
    
class Support_state(BaseModel):
    is_supported: Literal["fully", "partially", "no"] = Field(
            description = """
                Given the documents and and current candidate answer. Is this answer actually supported by the generated documents
                fully: Generated answer is fully supported by the given documents,
                partially: Generated answers are partialy supported by the given documents,
                no: Generated answers are not supported by the given documents.
                
            """
        )
    is_supported_feedback: str = Field(description= "why this answer is not supported for the retrieved docs")
    
class Usefulness_state(BaseModel):
    is_useful: Literal["1", "2", "3", "4", "5"] = Field(
            description= """
                Given the answer for the given query does the answer actually answers the given query on the scale of 1 to 5 
            """
        )
    is_useful_feedback: str = Field(description="useful answer or not feedback")

class Candidate_answer(BaseModel):
    answer: str = Field(description="Candidate answer generated by the LLM")
    source_doc_ids: List[str] = Field(default_factory=list, description="IDs of source documents used to generate the answer")
    support_state: Optional[Support_state] = Field(default = None, description="answers state about support")
    usefulness_state: Optional[Usefulness_state] = Field(default = None, description="answers state about usefulnees")

# Any field that isn't known at object-construction time — because it's 
# filled in by a later node in the graph — must be Optional[...] = None 
# (or have some other real default). A required field with no default forces
# you to know its value the instant the parent object is created, 
# which conflicts with a graph that fills in different pieces of state 
# incrementally, node by node.
    
class RAGState(BaseModel):
    query: str = Field(description="Initial User given query")
    query_retrieval_decision : Optional[bool] = Field(
        default = None,
        description="""Given the user query do we need to do the retrieval from the Retrivers from external 
                        Knowledge base or is the answer generation is self sufficient task which doesnt
                        requires any outside knowledge """
    )
    file_path: Optional[str] = Field(default=None, description="Path to file file on disk")
    file_ids: Optional[List[str]] = Field(default=None, description="Active file IDs for retrieval")
    context: List[Retrieved_docs] = Field(default_factory=list, description="Retrieved context chunks")
    relevant_context: List[Retrieved_docs] = Field(default_factory=list, description="Retrieved context chunks")
    candidate_answer: Optional[Candidate_answer] = Field(
        default=None, 
        description="Candidate answer generated by the LLM"
    )
    retries: int = 0
    revised_answer: Optional[Candidate_answer] = Field(
            default = None,
            description=""" 
                Given the query and candidate answer this is revised answer by reconsidering the retrieved documents because candidate answer doesnt seem to be 
                supported by the retrieved documents
            """
    )
    final_answer: Optional[Candidate_answer] = Field(
            default = None,
            description=""" 
                This is the final answer for the input query given by the user
            """
    )